apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-web-app
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=my-web-app'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
  providesApis:
  - my-web-app
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-web-app
  description: The API Provider
  tags:
    - api
    - tanzu
spec:
  type: openapi
  lifecycle: experimental
  owner: default-team
  definition:
    $text: https://github.com/trisberg/my-web-app/blob/main/api-docs.yaml
